#!/usr/bin /perl

use strict;
use warnings;
use feature 'say';

use Memoize;

memoize('fib');

my @fib;

sub fib {
  return 1 if $_[0] == 1;
  return 1 if $_[0] == 2;
  return fib($_[0] - 1) + fib($_[0] - 2);
}

my $total;
my $x = 1;

while (1) {
  my $fibx = fib($x);
  say "$x: $fibx";
  last if $fibx >= 4_000_000;
  $x++;
  next if $fibx % 2;
  $total += $fibx;
}

say $total;
