#!/usr/bin/perl

use strict;
use warnings;
use feature 'say';

my $target = 600851475143;
my @factors;

for (2 .. int(sqrt($target))) {
  next unless is_prime($_);
  next if $target % $_;
  push @factors, $_;
}

say "@factors";

sub is_prime {
  for (2 .. int(sqrt($_[0]))) {
    return unless $_[0] % $_;
  }
  return 1;
}
